# -*- coding: utf-8 -*-
with open('app_v6.js', 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_code_lines = [
    '    // テキストからデッキ読込\n',
    '    const btnImportText = document.getElementById(\'btn-import-text\');\n',
    '    if (btnImportText) {\n',
    '        btnImportText.addEventListener(\'click\', () => {\n',
    '            try {\n',
    '                const textArea = document.getElementById(\'import-text-area\');\n',
    '                const text = textArea.value;\n',
    '                if (!text.trim()) {\n',
    '                    alert("テキストを入力してください。");\n',
    '                    return;\n',
    '                }\n',
    '\n',
    '                // 全角記号を半角に正規化\n',
    '                const normalizedText = text.replace(/\\uff1a/g, \':\').replace(/\\uff08/g, \'(\').replace(/\\uff09/g, \')\');\n',
    '\n',
    '                // 能力値のパース\n',
    '                const statsMatch = normalizedText.match(/肉体:\\s*(\\d+)\\s*\\/\\s*知性:\\s*(\\d+)\\s*\\/\\s*精神:\\s*(\\d+)/);\n',
    '                if (statsMatch) {\n',
    '                    player.stats.body.maxVal = parseInt(statsMatch[1]);\n',
    '                    player.stats.body.currentVal = player.stats.body.maxVal;\n',
    '                    player.stats.int.maxVal = parseInt(statsMatch[2]);\n',
    '                    player.stats.int.currentVal = player.stats.int.maxVal;\n',
    '                    player.stats.men.maxVal = parseInt(statsMatch[3]);\n',
    '                    player.stats.men.currentVal = player.stats.men.maxVal;\n',
    '                }\n',
    '\n',
    '                // レベルのパース\n',
    '                const levelMatch = normalizedText.match(/レベル:\\s*(\\d+)/);\n',
    '                if (levelMatch) player.level = parseInt(levelMatch[1]);\n',
    '\n',
    '                // 手札上限のパース\n',
    '                const handMatch = normalizedText.match(/手札上限:\\s*(\\d+)/);\n',
    '                if (handMatch) player.maxHandSize = parseInt(handMatch[1]);\n',
    '\n',
    '                // デッキのパース\n',
    '                const newDeck = [];\n',
    '                const notFound = [];\n',
    '                const dLines = normalizedText.split(/\\r\\n|\\r|\\n/);\n',
    '                let inDeckSection = false;\n',
    '                \n',
    '                for (let line of dLines) {\n',
    '                    line = line.trim();\n',
    '                    if (line.startsWith(\'【デッキ内容\')) {\n',
    '                        inDeckSection = true;\n',
    '                        continue;\n',
    '                    }\n',
    '                    if (inDeckSection && line.startsWith(\'【\')) {\n',
    '                        inDeckSection = false;\n',
    '                        continue;\n',
    '                    }\n',
    '                    if (inDeckSection) {\n',
    '                        const cardMatch = line.match(/^(?:-|\\d+[.\\uFF0E])\\s*(.+?)\\s*\\(コスト:/);\n',
    '                        if (cardMatch) {\n',
    '                            const cardName = cardMatch[1].trim();\n',
    '                            const cardData = cardPool.find(c => c.name === cardName);\n',
    '                            if (cardData) {\n',
    '                                newDeck.push({ ...cardData });\n',
    '                            } else {\n',
    '                                notFound.push(cardName);\n',
    '                            }\n',
    '                        }\n',
    '                    }\n',
    '                }\n',
    '\n',
    '                // キャラクター設定のパース\n',
    '                const profileSection = normalizedText.match(/【キャラクター設定】([\\s\\S]*)/);\n',
    '                if (profileSection) {\n',
    '                    const profileText = profileSection[1];\n',
    '                    if (!player.profile) player.profile = {};\n',
    '                    \n',
    '                    const pMatch = (key, regex) => {\n',
    '                        const m = profileText.match(regex);\n',
    '                        if (m) player.profile[key] = m[1].trim();\n',
    '                    };\n',
    '                    pMatch(\'name\', /名前:\\s*(.+)/);\n',
    '                    if (player.profile.name) player.name = player.profile.name;\n',
    '                    pMatch(\'gender\', /性別:\\s*(.+)/);\n',
    '                    pMatch(\'age\', /年齢:\\s*(.+)/);\n',
    '                    pMatch(\'important\', /大事なもの:\\s*(.+)/);\n',
    '                    pMatch(\'dislike\', /嫌いなもの:\\s*(.+)/);\n',
    '                    pMatch(\'appearance\', /身長・体重・外見:\\s*(.+)/);\n',
    '                    pMatch(\'memo\', /メモ:\\s*(.+)/);\n',
    '                    \n',
    '                    for (let i = 1; i <= 10; i++) {\n',
    "                        pMatch('q' + i, new RegExp('Q' + i + ':\\\\s*(.+)'));\n",
    '                    }\n',
    '                }\n',
    '\n',
    '                if (newDeck.length > 0) {\n',
    '                    selectedCardsForDeck = newDeck;\n',
    '                    \n',
    '                    try { updateCharaUI(); } catch(e) { console.warn(\'updateCharaUI skipped:\', e); }\n',
    '                    renderSelectedDeck();\n',
    '                    els.loadModal.classList.add(\'hidden\');\n',
    '                    textArea.value = \'\';\n',
    '                    \n',
    '                    let msg = \'デッキの構築に成功しました！（\' + newDeck.length + \'枚のカードを読み込みました）\';\n',
    '                    if (notFound.length > 0) {\n',
    "                        msg += '\\n\\n⚠ 以下のカードは見つかりませんでした:\\n' + notFound.join('\\n');\n",
    '                    }\n',
    '                    alert(msg);\n',
    '                } else {\n',
    '                    alert("【エラー】カードが読み取れませんでした。\\n※「【デッキ内容」の行が含まれているか確認してください。");\n',
    '                }\n',
    '            } catch (err) {\n',
    '                alert("予期せぬエラー: " + err.message);\n',
    '                console.error(err);\n',
    '            }\n',
    '        });\n',
    '    }\n',
]

# Find where to replace. 
# We'll replace from `    // テキストからデッキ読込` until the next `    // イニシアチブ手動調整ボタン`
start_idx = -1
end_idx = -1
for i, line in enumerate(lines):
    if line.strip() == '// テキストからデッキ読込':
        start_idx = i
    if line.strip() == '// イニシアチブ手動調整ボタン（影縫い等の効果用）':
        end_idx = i
        break

if start_idx != -1 and end_idx != -1:
    new_lines = lines[:start_idx] + new_code_lines + lines[end_idx:]
    with open('app_v6.js', 'w', encoding='utf-8') as f:
        f.writelines(new_lines)
    print(f"DONE - replaced lines {start_idx} to {end_idx}")
else:
    print("ERROR: could not find indices")
